version: 2.1

jobs:
  test-and-lint:
  description: "Setup Django application, lint it and run tests"
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: pylint accounts core  mysite --ignore=migrations
      - run:
          name: run tests
          command: python manage.py test
  deploy-to-prod:
  machine:
      enabled: true
  steps:
      - run:
          name: Deploy Over SSH to Prod
          command: |
          ssh $SSH_USER@$SSH_HOST

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
      - deploy-to-prod