version: 2.1

jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST "cd docxify_api && sudo ./deploy.sh"

  test-and-lint:
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: pylint accounts core  mysite --ignore=migrations
      - run:
          name: run tests
          command: python manage.py test
     
workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint:
          filters:
            branches:
              only:
                - staging
      - pull-and-build:
          filters:
            branches:
              only:
                - main